name: 'tests'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: test
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    ports:
      - "3000:3000"