name: 'prod'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: $$RAILS_MASTER_KEY
    ports:
      - "3000:3000"