name: build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build prod Docker image
        uses: docker/build-push-action@v6
        with:
          image: ${{ github.event.repository.name }}/${{github.ref}}:${{ github.sha }}
          push: false
          file: Dockerfile.dev
