name: build

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build prod Docker image
        uses: docker/build-push-action@v6
        with:
          image: ${{ github.event.repository.name }}/${{github.ref}}:${{ github.sha }}
          push: false
          file: Dockerfile.dev
