name: build

on:
  workflow_dispatch:
  workflow_call:
    inputs: 
      docker_user_name:
        description: "Username to login to DockerHub"
        type: string
        required: true
    secrets:
      docker_access_token:
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_user_name }}
          password: ${{ secrets.docker_access_token }}
      
      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.event.repository.name }}/${{ github.ref }}:${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags:  ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY}}:latest
          file: Dockerfile.dev
