name: build

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3docker login -u tiagomadeiradock

      - name: Build prod Docker image
        uses: docker/build-push-action@v6
        with:
          image: ${{ github.event.repository.name }}/${{github.ref}}:${{ github.sha }}
          push: true
          file: Dockerfile.dev
