name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  scan_ruby:
    uses: ./.github/workflows/scan.yml

  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml
    depends_on: [scan_ruby, lint, test]
  
