name: deploy-app

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: "Enviorment you wish to deploy to"
        options:
          - test
          - staging
          - production
        default: staging
      image:
        required: true
        description: "Tag or sha of the image you wish to deploy"

jobs:
    deploy:
      uses: CarrentalsOrg/ReusableWorkflows/.github/workflows/deploy.yml@v2
      with:
        environment: ${{github.event.inputs.environment}}
        image: ${{github.event.inputs.environment}}
        dockerhub_repo: ${{vars.DOCKERHUB_REPOSITORY}}
      secrets:
        gitops_token: ${{secrets.GITOPS_TOKEN}}