name: fix-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: CarrentalsOrg/CarrentalsK8sConfigfffff
          ref: master
          token: ${{secrets.GITOPS_TOKEN}}
