name: test

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y  curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup Database
        run: |
          bundle exec rails db:schema:load
          bundle exec rails db:migrate

      - name: Run tests   
        run: bundle exec rspec