name: test

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y  curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup Database
        run: |
          bundle exec rails parallel:load_schema
          bundle exec rails parallel:migrate

      - name: Run tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          DEVISE_JWT_SECRET_KEY: ${{secrets.DEVISE_JWT_SECRET_KEY}}
        run: bundle exec rspec